# Site
name: 'boostheight'
description: 'Truyền cảm hứng, dẫn dắt tương lai: Nâng cao thể chất người Việt!'
logo: assets/images/logo/logo-home.webp
favicon: 'assets/images/favicon.png'
baseurl: ""
# disqus: 'demowebsite'
email: 'boostheightjsc@gmail.com'
mailchimp-list: 'https://formspree.io/f/xqakpgyn'

include: ["_pages"]
permalink: /:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    boostheight:
      name:           boostheight
      site:           welcome-to-boostheight
      avatar:         assets/images/avatar1.webp
      bio:            "Truyền cảm hứng, dẫn dắt tương lai: Nâng cao thể chất người Việt!"
      email:          boostheightjsc@gmail.com
      instagram:        https://www.instagram.com/boostheight_ig/
      pinterest:        https://www.pinterest.com/boostheightjsc/
      tiktok:        https://www.tiktok.com/@boostheight.com
      facebook:        https://www.facebook.com/people/Boost-Height/61578968544858/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: boostheight
      avatar: assets/images/avatar1.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 8



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]